import Foundation

/// Decides whether a pasteboard change may be recorded. Pure, so it's unit-tested.
enum ClipboardFilter {
    /// Markers from the nspasteboard.org convention. Password managers set `ConcealedType`;
    /// `TransientType` and `AutoGeneratedType` mark data the user never meant to keep.
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    static func shouldCapture(types: [String], sourceBundleID: String?, blocklist: Set<String>) -> Bool {
        guard !types.isEmpty else { return false }
        if types.contains(where: excludedTypes.contains) {
            return false
        }
        if let sourceBundleID, blocklist.contains(sourceBundleID) {
            return false
        }
        return true
    }
}
