import XCTest
@testable import FeatureClipboard

final class ClipboardFilterTests: XCTestCase {
    private let blocklist: Set<String> = ["com.1password.1password"]

    func testOrdinaryTextIsCaptured() {
        XCTAssertTrue(ClipboardFilter.shouldCapture(
            types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.TextEdit", blocklist: blocklist
        ))
    }

    func testConcealedTypeIsRejected() {
        XCTAssertFalse(ClipboardFilter.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            sourceBundleID: "com.example.app", blocklist: blocklist
        ))
    }

    func testTransientAndAutoGeneratedAreRejected() {
        XCTAssertFalse(ClipboardFilter.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"], sourceBundleID: nil, blocklist: []
        ))
        XCTAssertFalse(ClipboardFilter.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"], sourceBundleID: nil, blocklist: []
        ))
    }

    func testBlocklistedSourceIsRejected() {
        XCTAssertFalse(ClipboardFilter.shouldCapture(
            types: ["public.utf8-plain-text"], sourceBundleID: "com.1password.1password", blocklist: blocklist
        ))
    }

    func testEmptyPasteboardIsRejected() {
        XCTAssertFalse(ClipboardFilter.shouldCapture(types: [], sourceBundleID: nil, blocklist: []))
    }
}

final class ClipboardStoreTests: XCTestCase {
    private var root: URL!

    override func setUpWithError() throws {
        root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: root)
    }

    func testRepeatedCopyMovesToTopInsteadOfDuplicating() {
        let store = ClipboardStore(root: root)
        store.add(ClipEntry(kind: .text, text: "hello", byteSize: 5))
        store.add(ClipEntry(kind: .text, text: "world", byteSize: 5))
        store.add(ClipEntry(kind: .text, text: "hello", byteSize: 5))
        XCTAssertEqual(store.entries.map(\.text), ["hello", "world"])
    }

    func testCapByCountDropsOldest() {
        let store = ClipboardStore(root: root, maxItems: 2)
        store.add(ClipEntry(kind: .text, text: "1"))
        store.add(ClipEntry(kind: .text, text: "2"))
        store.add(ClipEntry(kind: .text, text: "3"))
        XCTAssertEqual(store.entries.map(\.text), ["3", "2"])
    }

    func testCapByBytesDropsOldest() {
        let store = ClipboardStore(root: root, maxItems: 100, maxBytes: 10)
        store.add(ClipEntry(kind: .text, text: "old", byteSize: 8))
        store.add(ClipEntry(kind: .text, text: "new", byteSize: 8))
        XCTAssertEqual(store.entries.map(\.text), ["new"])
    }

    func testHistorySurvivesReload() {
        let store = ClipboardStore(root: root)
        store.add(ClipEntry(kind: .files, filePaths: ["/tmp/a.txt"]))
        store.add(ClipEntry(kind: .text, text: "note"))
        let reloaded = ClipboardStore(root: root)
        XCTAssertEqual(reloaded.entries.count, 2)
        XCTAssertEqual(reloaded.entries.first?.text, "note")
    }

    func testImageBlobIsStoredAndDeleted() throws {
        let store = ClipboardStore(root: root)
        let entry = ClipEntry(kind: .image, byteSize: 3)
        store.add(entry, imageData: Data([1, 2, 3]))
        let name = try XCTUnwrap(store.entries.first?.imageFileName)
        XCTAssertTrue(FileManager.default.fileExists(atPath: store.blobURL(name).path))
        store.removeAll()
        XCTAssertFalse(FileManager.default.fileExists(atPath: store.blobURL(name).path))
    }

    func testDirectoryIsPrivateAndExcludedFromSpotlight() throws {
        _ = ClipboardStore(root: root)
        let attributes = try FileManager.default.attributesOfItem(atPath: root.path)
        XCTAssertEqual((attributes[.posixPermissions] as? NSNumber)?.intValue, 0o700)
        XCTAssertTrue(FileManager.default.fileExists(atPath: root.appendingPathComponent(".metadata_never_index").path))
    }

    func testSearchMatchesPreviewAndSource() {
        let entry = ClipEntry(kind: .text, text: "Invoice #42\nTotal", sourceAppName: "Mail")
        XCTAssertTrue(entry.matches("invoice"))
        XCTAssertTrue(entry.matches("mail"))
        XCTAssertFalse(entry.matches("safari"))
        XCTAssertEqual(entry.preview, "Invoice #42 Total")
    }
}
